name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks a lot for the effort, your issue is under review. Please be patient, we will check it and get back to you soon!'
        pr-message: 'Thanks a lot for the effort, your pull-request is under review.'
